# Generated by Django 5.0.1 on 2025-06-26 04:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='kategori/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='konten',
            field=django_ckeditor_5.fields.CKEditor5Field(default='konten belum diisi', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
